//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S00Presentacion.WCFServicio {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFServicio.IServicios")]
    public interface IServicios {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/BancoExternoAgregar", ReplyAction="http://tempuri.org/IServicios/BancoExternoAgregarResponse")]
        void BancoExternoAgregar(S04Entidades.BancoExteno externo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/BancoExternoAgregar", ReplyAction="http://tempuri.org/IServicios/BancoExternoAgregarResponse")]
        System.Threading.Tasks.Task BancoExternoAgregarAsync(S04Entidades.BancoExteno externo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/BancoExternoModificar", ReplyAction="http://tempuri.org/IServicios/BancoExternoModificarResponse")]
        void BancoExternoModificar(S04Entidades.BancoExteno externo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/BancoExternoModificar", ReplyAction="http://tempuri.org/IServicios/BancoExternoModificarResponse")]
        System.Threading.Tasks.Task BancoExternoModificarAsync(S04Entidades.BancoExteno externo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/BancoExternoEliminar", ReplyAction="http://tempuri.org/IServicios/BancoExternoEliminarResponse")]
        void BancoExternoEliminar(S04Entidades.BancoExteno externo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/BancoExternoEliminar", ReplyAction="http://tempuri.org/IServicios/BancoExternoEliminarResponse")]
        System.Threading.Tasks.Task BancoExternoEliminarAsync(S04Entidades.BancoExteno externo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/ClienteAgregar", ReplyAction="http://tempuri.org/IServicios/ClienteAgregarResponse")]
        void ClienteAgregar(S04Entidades.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/ClienteAgregar", ReplyAction="http://tempuri.org/IServicios/ClienteAgregarResponse")]
        System.Threading.Tasks.Task ClienteAgregarAsync(S04Entidades.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/ClienteModificar", ReplyAction="http://tempuri.org/IServicios/ClienteModificarResponse")]
        void ClienteModificar(S04Entidades.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/ClienteModificar", ReplyAction="http://tempuri.org/IServicios/ClienteModificarResponse")]
        System.Threading.Tasks.Task ClienteModificarAsync(S04Entidades.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/ClienteEliminar", ReplyAction="http://tempuri.org/IServicios/ClienteEliminarResponse")]
        void ClienteEliminar(S04Entidades.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/ClienteEliminar", ReplyAction="http://tempuri.org/IServicios/ClienteEliminarResponse")]
        System.Threading.Tasks.Task ClienteEliminarAsync(S04Entidades.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/ClienteBuscar", ReplyAction="http://tempuri.org/IServicios/ClienteBuscarResponse")]
        System.Collections.Generic.List<S04Entidades.Cliente> ClienteBuscar(S04Entidades.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/ClienteBuscar", ReplyAction="http://tempuri.org/IServicios/ClienteBuscarResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<S04Entidades.Cliente>> ClienteBuscarAsync(S04Entidades.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/ServicioAgregar", ReplyAction="http://tempuri.org/IServicios/ServicioAgregarResponse")]
        void ServicioAgregar(S04Entidades.Servicio servicio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/ServicioAgregar", ReplyAction="http://tempuri.org/IServicios/ServicioAgregarResponse")]
        System.Threading.Tasks.Task ServicioAgregarAsync(S04Entidades.Servicio servicio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/ServicioModificar", ReplyAction="http://tempuri.org/IServicios/ServicioModificarResponse")]
        void ServicioModificar(S04Entidades.Servicio servicio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/ServicioModificar", ReplyAction="http://tempuri.org/IServicios/ServicioModificarResponse")]
        System.Threading.Tasks.Task ServicioModificarAsync(S04Entidades.Servicio servicio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/ServicioEliminar", ReplyAction="http://tempuri.org/IServicios/ServicioEliminarResponse")]
        void ServicioEliminar(S04Entidades.Servicio servicio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/ServicioEliminar", ReplyAction="http://tempuri.org/IServicios/ServicioEliminarResponse")]
        System.Threading.Tasks.Task ServicioEliminarAsync(S04Entidades.Servicio servicio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/UsuarioAgregar", ReplyAction="http://tempuri.org/IServicios/UsuarioAgregarResponse")]
        void UsuarioAgregar(S04Entidades.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/UsuarioAgregar", ReplyAction="http://tempuri.org/IServicios/UsuarioAgregarResponse")]
        System.Threading.Tasks.Task UsuarioAgregarAsync(S04Entidades.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/UsuarioModificar", ReplyAction="http://tempuri.org/IServicios/UsuarioModificarResponse")]
        void UsuarioModificar(S04Entidades.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/UsuarioModificar", ReplyAction="http://tempuri.org/IServicios/UsuarioModificarResponse")]
        System.Threading.Tasks.Task UsuarioModificarAsync(S04Entidades.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/UsuarioEliminar", ReplyAction="http://tempuri.org/IServicios/UsuarioEliminarResponse")]
        void UsuarioEliminar(S04Entidades.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/UsuarioEliminar", ReplyAction="http://tempuri.org/IServicios/UsuarioEliminarResponse")]
        System.Threading.Tasks.Task UsuarioEliminarAsync(S04Entidades.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/UsuarioBuscar", ReplyAction="http://tempuri.org/IServicios/UsuarioBuscarResponse")]
        System.Collections.Generic.List<S04Entidades.Usuario> UsuarioBuscar(S04Entidades.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/UsuarioBuscar", ReplyAction="http://tempuri.org/IServicios/UsuarioBuscarResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<S04Entidades.Usuario>> UsuarioBuscarAsync(S04Entidades.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/AbonoRetiroInterno", ReplyAction="http://tempuri.org/IServicios/AbonoRetiroInternoResponse")]
        void AbonoRetiroInterno(S04Entidades.Cliente abonoRetiroI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/AbonoRetiroInterno", ReplyAction="http://tempuri.org/IServicios/AbonoRetiroInternoResponse")]
        System.Threading.Tasks.Task AbonoRetiroInternoAsync(S04Entidades.Cliente abonoRetiroI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/AbonoRetiroExterno", ReplyAction="http://tempuri.org/IServicios/AbonoRetiroExternoResponse")]
        void AbonoRetiroExterno(S04Entidades.Cliente abonoRetiroE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/AbonoRetiroExterno", ReplyAction="http://tempuri.org/IServicios/AbonoRetiroExternoResponse")]
        System.Threading.Tasks.Task AbonoRetiroExternoAsync(S04Entidades.Cliente abonoRetiroE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/MontosGlobales", ReplyAction="http://tempuri.org/IServicios/MontosGlobalesResponse")]
        System.Collections.Generic.List<S04Entidades.Cliente> MontosGlobales();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/MontosGlobales", ReplyAction="http://tempuri.org/IServicios/MontosGlobalesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<S04Entidades.Cliente>> MontosGlobalesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/EstadosdeCuenta", ReplyAction="http://tempuri.org/IServicios/EstadosdeCuentaResponse")]
        System.Collections.Generic.List<S04Entidades.Transaccion> EstadosdeCuenta(S04Entidades.Transaccion EstCuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/EstadosdeCuenta", ReplyAction="http://tempuri.org/IServicios/EstadosdeCuentaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<S04Entidades.Transaccion>> EstadosdeCuentaAsync(S04Entidades.Transaccion EstCuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/VerEstadoUsuarios", ReplyAction="http://tempuri.org/IServicios/VerEstadoUsuariosResponse")]
        System.Collections.Generic.List<S04Entidades.Usuario> VerEstadoUsuarios(S04Entidades.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/VerEstadoUsuarios", ReplyAction="http://tempuri.org/IServicios/VerEstadoUsuariosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<S04Entidades.Usuario>> VerEstadoUsuariosAsync(S04Entidades.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/VerEstadoClientes", ReplyAction="http://tempuri.org/IServicios/VerEstadoClientesResponse")]
        System.Collections.Generic.List<S04Entidades.Cliente> VerEstadoClientes(S04Entidades.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/VerEstadoClientes", ReplyAction="http://tempuri.org/IServicios/VerEstadoClientesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<S04Entidades.Cliente>> VerEstadoClientesAsync(S04Entidades.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/TransaccionesRegistradas", ReplyAction="http://tempuri.org/IServicios/TransaccionesRegistradasResponse")]
        System.Collections.Generic.List<S04Entidades.Transaccion> TransaccionesRegistradas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/TransaccionesRegistradas", ReplyAction="http://tempuri.org/IServicios/TransaccionesRegistradasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<S04Entidades.Transaccion>> TransaccionesRegistradasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/ConsultaSaldos", ReplyAction="http://tempuri.org/IServicios/ConsultaSaldosResponse")]
        System.Collections.Generic.List<S04Entidades.Cliente> ConsultaSaldos(S04Entidades.Cliente saldos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/ConsultaSaldos", ReplyAction="http://tempuri.org/IServicios/ConsultaSaldosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<S04Entidades.Cliente>> ConsultaSaldosAsync(S04Entidades.Cliente saldos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/Login", ReplyAction="http://tempuri.org/IServicios/LoginResponse")]
        System.Collections.Generic.List<S04Entidades.Usuario> Login(S04Entidades.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/Login", ReplyAction="http://tempuri.org/IServicios/LoginResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<S04Entidades.Usuario>> LoginAsync(S04Entidades.Usuario usuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiciosChannel : S00Presentacion.WCFServicio.IServicios, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiciosClient : System.ServiceModel.ClientBase<S00Presentacion.WCFServicio.IServicios>, S00Presentacion.WCFServicio.IServicios {
        
        public ServiciosClient() {
        }
        
        public ServiciosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiciosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void BancoExternoAgregar(S04Entidades.BancoExteno externo) {
            base.Channel.BancoExternoAgregar(externo);
        }
        
        public System.Threading.Tasks.Task BancoExternoAgregarAsync(S04Entidades.BancoExteno externo) {
            return base.Channel.BancoExternoAgregarAsync(externo);
        }
        
        public void BancoExternoModificar(S04Entidades.BancoExteno externo) {
            base.Channel.BancoExternoModificar(externo);
        }
        
        public System.Threading.Tasks.Task BancoExternoModificarAsync(S04Entidades.BancoExteno externo) {
            return base.Channel.BancoExternoModificarAsync(externo);
        }
        
        public void BancoExternoEliminar(S04Entidades.BancoExteno externo) {
            base.Channel.BancoExternoEliminar(externo);
        }
        
        public System.Threading.Tasks.Task BancoExternoEliminarAsync(S04Entidades.BancoExteno externo) {
            return base.Channel.BancoExternoEliminarAsync(externo);
        }
        
        public void ClienteAgregar(S04Entidades.Cliente cliente) {
            base.Channel.ClienteAgregar(cliente);
        }
        
        public System.Threading.Tasks.Task ClienteAgregarAsync(S04Entidades.Cliente cliente) {
            return base.Channel.ClienteAgregarAsync(cliente);
        }
        
        public void ClienteModificar(S04Entidades.Cliente cliente) {
            base.Channel.ClienteModificar(cliente);
        }
        
        public System.Threading.Tasks.Task ClienteModificarAsync(S04Entidades.Cliente cliente) {
            return base.Channel.ClienteModificarAsync(cliente);
        }
        
        public void ClienteEliminar(S04Entidades.Cliente cliente) {
            base.Channel.ClienteEliminar(cliente);
        }
        
        public System.Threading.Tasks.Task ClienteEliminarAsync(S04Entidades.Cliente cliente) {
            return base.Channel.ClienteEliminarAsync(cliente);
        }
        
        public System.Collections.Generic.List<S04Entidades.Cliente> ClienteBuscar(S04Entidades.Cliente cliente) {
            return base.Channel.ClienteBuscar(cliente);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<S04Entidades.Cliente>> ClienteBuscarAsync(S04Entidades.Cliente cliente) {
            return base.Channel.ClienteBuscarAsync(cliente);
        }
        
        public void ServicioAgregar(S04Entidades.Servicio servicio) {
            base.Channel.ServicioAgregar(servicio);
        }
        
        public System.Threading.Tasks.Task ServicioAgregarAsync(S04Entidades.Servicio servicio) {
            return base.Channel.ServicioAgregarAsync(servicio);
        }
        
        public void ServicioModificar(S04Entidades.Servicio servicio) {
            base.Channel.ServicioModificar(servicio);
        }
        
        public System.Threading.Tasks.Task ServicioModificarAsync(S04Entidades.Servicio servicio) {
            return base.Channel.ServicioModificarAsync(servicio);
        }
        
        public void ServicioEliminar(S04Entidades.Servicio servicio) {
            base.Channel.ServicioEliminar(servicio);
        }
        
        public System.Threading.Tasks.Task ServicioEliminarAsync(S04Entidades.Servicio servicio) {
            return base.Channel.ServicioEliminarAsync(servicio);
        }
        
        public void UsuarioAgregar(S04Entidades.Usuario usuario) {
            base.Channel.UsuarioAgregar(usuario);
        }
        
        public System.Threading.Tasks.Task UsuarioAgregarAsync(S04Entidades.Usuario usuario) {
            return base.Channel.UsuarioAgregarAsync(usuario);
        }
        
        public void UsuarioModificar(S04Entidades.Usuario usuario) {
            base.Channel.UsuarioModificar(usuario);
        }
        
        public System.Threading.Tasks.Task UsuarioModificarAsync(S04Entidades.Usuario usuario) {
            return base.Channel.UsuarioModificarAsync(usuario);
        }
        
        public void UsuarioEliminar(S04Entidades.Usuario usuario) {
            base.Channel.UsuarioEliminar(usuario);
        }
        
        public System.Threading.Tasks.Task UsuarioEliminarAsync(S04Entidades.Usuario usuario) {
            return base.Channel.UsuarioEliminarAsync(usuario);
        }
        
        public System.Collections.Generic.List<S04Entidades.Usuario> UsuarioBuscar(S04Entidades.Usuario usuario) {
            return base.Channel.UsuarioBuscar(usuario);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<S04Entidades.Usuario>> UsuarioBuscarAsync(S04Entidades.Usuario usuario) {
            return base.Channel.UsuarioBuscarAsync(usuario);
        }
        
        public void AbonoRetiroInterno(S04Entidades.Cliente abonoRetiroI) {
            base.Channel.AbonoRetiroInterno(abonoRetiroI);
        }
        
        public System.Threading.Tasks.Task AbonoRetiroInternoAsync(S04Entidades.Cliente abonoRetiroI) {
            return base.Channel.AbonoRetiroInternoAsync(abonoRetiroI);
        }
        
        public void AbonoRetiroExterno(S04Entidades.Cliente abonoRetiroE) {
            base.Channel.AbonoRetiroExterno(abonoRetiroE);
        }
        
        public System.Threading.Tasks.Task AbonoRetiroExternoAsync(S04Entidades.Cliente abonoRetiroE) {
            return base.Channel.AbonoRetiroExternoAsync(abonoRetiroE);
        }
        
        public System.Collections.Generic.List<S04Entidades.Cliente> MontosGlobales() {
            return base.Channel.MontosGlobales();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<S04Entidades.Cliente>> MontosGlobalesAsync() {
            return base.Channel.MontosGlobalesAsync();
        }
        
        public System.Collections.Generic.List<S04Entidades.Transaccion> EstadosdeCuenta(S04Entidades.Transaccion EstCuenta) {
            return base.Channel.EstadosdeCuenta(EstCuenta);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<S04Entidades.Transaccion>> EstadosdeCuentaAsync(S04Entidades.Transaccion EstCuenta) {
            return base.Channel.EstadosdeCuentaAsync(EstCuenta);
        }
        
        public System.Collections.Generic.List<S04Entidades.Usuario> VerEstadoUsuarios(S04Entidades.Usuario usuario) {
            return base.Channel.VerEstadoUsuarios(usuario);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<S04Entidades.Usuario>> VerEstadoUsuariosAsync(S04Entidades.Usuario usuario) {
            return base.Channel.VerEstadoUsuariosAsync(usuario);
        }
        
        public System.Collections.Generic.List<S04Entidades.Cliente> VerEstadoClientes(S04Entidades.Cliente cliente) {
            return base.Channel.VerEstadoClientes(cliente);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<S04Entidades.Cliente>> VerEstadoClientesAsync(S04Entidades.Cliente cliente) {
            return base.Channel.VerEstadoClientesAsync(cliente);
        }
        
        public System.Collections.Generic.List<S04Entidades.Transaccion> TransaccionesRegistradas() {
            return base.Channel.TransaccionesRegistradas();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<S04Entidades.Transaccion>> TransaccionesRegistradasAsync() {
            return base.Channel.TransaccionesRegistradasAsync();
        }
        
        public System.Collections.Generic.List<S04Entidades.Cliente> ConsultaSaldos(S04Entidades.Cliente saldos) {
            return base.Channel.ConsultaSaldos(saldos);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<S04Entidades.Cliente>> ConsultaSaldosAsync(S04Entidades.Cliente saldos) {
            return base.Channel.ConsultaSaldosAsync(saldos);
        }
        
        public System.Collections.Generic.List<S04Entidades.Usuario> Login(S04Entidades.Usuario usuario) {
            return base.Channel.Login(usuario);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<S04Entidades.Usuario>> LoginAsync(S04Entidades.Usuario usuario) {
            return base.Channel.LoginAsync(usuario);
        }
    }
}
