//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S04Entidades
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class Servicio
    {
        public int IdSevicio { get; set; }
        public string DescServicio { get; set; }
        public bool Estado { get; set; }
    }
}
