//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S04Entidades
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class Usuario
    {
        public string Usuario1 { get; set; }
        public string Nombre { get; set; }
        public string Contrasena { get; set; }
        public bool Estado { get; set; }
    }
}
